//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterpressExam.Service.Windows.Downloader.ListenSrvRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListenSrvRef.IListenService")]
    public interface IListenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListenService/FireDatabaseEvents", ReplyAction="http://tempuri.org/IListenService/FireDatabaseEventsResponse")]
        void FireDatabaseEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListenService/FireDatabaseEvents", ReplyAction="http://tempuri.org/IListenService/FireDatabaseEventsResponse")]
        System.Threading.Tasks.Task FireDatabaseEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListenService/BroadcastToClients", ReplyAction="http://tempuri.org/IListenService/BroadcastToClientsResponse")]
        void BroadcastToClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListenService/BroadcastToClients", ReplyAction="http://tempuri.org/IListenService/BroadcastToClientsResponse")]
        System.Threading.Tasks.Task BroadcastToClientsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListenServiceChannel : InterpressExam.Service.Windows.Downloader.ListenSrvRef.IListenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListenServiceClient : System.ServiceModel.ClientBase<InterpressExam.Service.Windows.Downloader.ListenSrvRef.IListenService>, InterpressExam.Service.Windows.Downloader.ListenSrvRef.IListenService {
        
        public ListenServiceClient() {
        }
        
        public ListenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void FireDatabaseEvents() {
            base.Channel.FireDatabaseEvents();
        }
        
        public System.Threading.Tasks.Task FireDatabaseEventsAsync() {
            return base.Channel.FireDatabaseEventsAsync();
        }
        
        public void BroadcastToClients() {
            base.Channel.BroadcastToClients();
        }
        
        public System.Threading.Tasks.Task BroadcastToClientsAsync() {
            return base.Channel.BroadcastToClientsAsync();
        }
    }
}
